Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,6 +30,23 @@ jobs:
     - name: Autopep8 (Auto format code)
       run: |
         autopep8 --in-place --aggressive --aggressive hw2_debugging.py rand.py
+        exit_code=$?
+        if [ $exit_code -eq 0 ]; then
+          echo "AUTOPEP8_STATUS=Pass" >> $GITHUB_ENV
+        else
+          echo "AUTOPEP8_STATUS=Fail" >> $GITHUB_ENV
+        fi
+        
+    - name: Create AutoPEP8 Badge
+      uses: schneegans/dynamic-badges-action@v1.7.0
+      with:
+        auth: ${{ secrets.GIST_SECRET }}
+        gistID: 610c5444484d8b7e11764786357f1075
+        filename: autopep8.json
+        label: AutoPEP8
+        message: ${{ env.AUTOPEP8_STATUS }}
+        color: ${{ env.AUTOPEP8_STATUS == 'Pass' && 'green' || 'red' }}
+
 
     - name: Run Pylint (Static analysis)
       run: |
@@ -40,28 +57,55 @@ jobs:
         else
           echo "PYLINT_STATUS=Fail" >> $GITHUB_ENV
         fi
-    - name: Debug Gist Update
-      run: |
-        echo "Auth Token: ${{ secrets.GIST_SECRET }}"
-        echo "Gist ID: eda49634ad4b5d5f829e8ade4d6f138c"
-        curl -H "Authorization: token ${{ secrets.GIST_SECRET }}" https://api.github.com/gists/eda49634ad4b5d5f829e8ade4d6f138c
-          
+            
     - name: Create Pylint Badge
+      uses: schneegans/dynamic-badges-action@v1.7.0
+      with:
+        auth: ${{ secrets.GIST_SECRET }}
+        gistID: 08bfddaeaa50b18120b40f0118cc6228
+        filename: pylint.json
+        label: Pylint
+        message: ${{ env.PYLINT_STATUS }}
+        color: ${{ env.PYLINT_STATUS == 'Pass' ? 'green' || 'red' }}
+
+    - name: Run pyright (Style check)
+      run: |
+        pyright hw2_debugging.py rand.py
+         exit_code=$?
+        if [ $exit_code -eq 0 ]; then
+          echo "PYRIGHT_STATUS=Pass" >> $GITHUB_ENV
+        else
+          echo "PYRIGHT_STATUS=Fail" >> $GITHUB_ENV
+        fi
+        
+    - name: Create Pyright Badge
       uses: schneegans/dynamic-badges-action@v1.7.0
       with:
         auth: ${{ secrets.GIST_SECRET }}
         gistID: eda49634ad4b5d5f829e8ade4d6f138c
         filename: pyright.json
         label: Pylint
-        message: hello
-        color: blue
-    #    forceUpdate: true
-
-    - name: Run pyright (Style check)
-      run: |
-        pyright hw2_debugging.py rand.py
+        message: ${{ env.PYRIGHT_STATUS }}
+        color: ${{ env.PYRIGHT_STATUS == 'Pass' ? 'green' || 'red' }}
 
     - name: Run Tests with pytest
       run: |
         pytest
+         exit_code=$?
+        if [ $exit_code -eq 0 ]; then
+          echo "PYTEST_STATUS=Pass" >> $GITHUB_ENV
+        else
+          echo "PYTEST_STATUS=Fail" >> $GITHUB_ENV
+        fi
+     # Create Pytest Badge
+    - name: Create Pytest Badge
+      uses: schneegans/dynamic-badges-action@v1.7.0
+      with:
+        auth: ${{ secrets.GIST_SECRET }}
+        gistID: a9e2ae393657421b37b65cc6d8c3756e
+        filename: pytest.json
+        label: Pytest
+        message: ${{ env.PYTEST_STATUS }}
+        color: ${{ env.PYTEST_STATUS == 'Pass' && 'green' || 'red' }}
+      
 
